### ISSUE TITLE
Warnings with cppyy 3.0.0

### ISSUE THREAD

**Issue by Prezma** [ogdf/ogdf-python#4]
Using `ogdf-python` in a jupyter-notebook with cppyy version 3.0.0 generates the following warnings (but produces the expected results):
![image](https://user-images.githubusercontent.com/56546894/230376808-fa11346b-094c-4ef6-9d4a-1c1512acae89.png)
When downgrading to cppyy version 2.4.1, these warnings disappear.

**Comment by N-Coder** [comment]
This is an issue with the underlying `cppyy` library independent of the OGDF which is tracked as https://github.com/wlav/cppyy/issues/175 and https://github.com/wlav/cppyy/issues/156. When installing `ogdf-python[quickstart]`, we now automatically select a cppyy version less than 3 which doesn't have this problem.

**Comment by N-Coder** [comment]
Resolved with cppyy 3.1.1 and ogdf-python 0.3.1 (version number sync-up unintended 😅 )
